name: ci
run-name: CI pipeline for Urbancode.DynamicIPService
on: 
  push:
    branches:
      - 'main'
jobs:
  test-job:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5
      - run: bash "Hello world"
